- name: Set Natural Scrolling to False
  command: defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false
  changed_when: true

- name: Check if .zsh_history file exists
  stat:
    path: "{{ ansible_env.HOME }}/.zsh_history"
  register: zshHistoryStat

- name: Copy or Concatenate .zsh_history
  block:
    - name: Copy .zsh_history if it doesn't exist
      copy:
        src: ../../configFIles/zsh/.zsh_history
        dest: "{{ ansible_env.HOME }}/.zsh_history"
      when: not zshHistoryStat.stat.exists

    - name: Concatenate .zsh_history if it exists
      shell: cat ../../configFIles/zsh/.zsh_history >> "{{ ansible_env.HOME }}/.zsh_history"
      when: zshHistoryStat.stat.exists
  when: zshHistoryStat.stat.exists | bool

- name: Check if .zshrc file exists
  stat:
    path: "{{ ansible_env.HOME }}/.zshrc"
  register: zshrcStat

- name: copy zshrc
  copy:
    src: ../../configFIles/zsh/.zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
  when: not zshrcStat.stat.exists